version: "3"

services:
  server:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./server
    container_name: server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/skribbl
      - SPRING_DATASOURCE_USERNAME=gosho
      - SPRING_DATASOURCE_PASSWORD=losho
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gosho
      - POSTGRES_PASSWORD=losho
      - POSTGRES_DB=skribbl
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # nginx:
  #   image: nginx:stable
  #   restart: "no"
  #   volumes:
  #     - ./data/nginx/dev.conf:/etc/nginx/conf.d/dev.conf
  #   depends_on:
  #     - orders-service
  #     - delivery-service
  #     - logger-service
  #     - users-service
  #   ports:
  #     - 80:80
  #     - 443:443